### ISSUE TITLE
Is the project abandoned ? Is it possible to take back ?

### ISSUE THREAD

**Issue by frju365** [suyashmahar/europa#3]
Hello @suyashmahar,

I'm Julien (frju365), I'm french. 

I think Europa is really helpful, and I use it today and will use it in computer engineer course next school year. I'm dev and adminsys.

However I wanted to know if you gave up the project or if some ppl are still updating it ? If not, it would be a pleasure for me to take back the project if you want.

Thanks in advance for your answer,

frju365

**Comment by suyashmahar** [comment]
Hi Julien, 

Thank you for your interest in Europa! PRs are always welcome :)

I'm not *actively* working on Europa at the moment (although I see this changing before the end of 2021). 

Also, I'm sorry, I missed your PR. I have merged #2 now. Thank you!

**Comment by frju365** [comment]
Thanks. I will try to contribute and add new feature if I find one in using it :)
