### ISSUE TITLE
Add a shift+right click menu for copying text in terminals

### ISSUE THREAD

**Issue by zer0-memory** [suyashmahar/europa#7]
Selecting text and attempting to copy it in a JupyterLab terminal with Ctrl+C sometimes sends a SIGTERM signal to the running program instead of copying the text. Selecting text within the terminal window should stop a SIGTERM from being sent to the running program, however for some reason JupyterLab doesn't always work that way.
In a web browser it isn't an issue, as we can still copy by selecting the text, pressing shift+right click (which opens the browsers native right click menu), and using the "Copy" option from the browser menu. Since Europa doesn't have a native right click menu, this workaround doesn't work.
It would be great if this could be added to Europa, as I frequently have to copy output from my terminal windows and I haven't been able to find any definitive workaround/reason for why using Ctrl+C doesn't always work.

**Comment by suyashmahar** [comment]
This is something that is on my radar for a while, quick look at electron (which is what europa is built on) suggests that it doesn't support that. 

Adding a fake context menu might be possible in either case. I'll take another look.

Thanks!

**Comment by suyashmahar** [comment]
You know what, I just tried [electron-context-menu](https://github.com/sindresorhus/electron-context-menu) and it works, I'll push a new version soon.

**Comment by zer0-memory** [comment]
Works great, thanks for the fix!
